# Base image with Python and dependencies installed
FROM tiangolo/uvicorn-gunicorn-fastapi:python3.9 as base

FROM base as dev

COPY ./app /app
WORKDIR /app

RUN pip install -r requirements-dev.txt

ENV PORT=8080

EXPOSE 8080

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8080", "--reload"]