FROM tiangolo/uvicorn-gunicorn-fastapi:python3.9

COPY ./app /app
WORKDIR /app

RUN pip install -r requirements.txt

ENV PORT=8080

EXPOSE 8080

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]